name: techtalk
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Chat GPT
  chatgpt_completions: ^0.0.5

  # UI
  cupertino_will_pop_scope: ^1.2.1  #pop scope (스와이프 백 제스쳐 지원)
  after_layout: ^1.2.0 # Widget LifeCycle Mixin
  flutter_svg: ^2.0.5 # SVG 아이콘
  flutter_easyloading: ^3.0.5 # 로딩 UI 처리 관련
  flutter_chat_bubble: ^2.0.2 # 말풍선
  provider_screen: ^1.0.0 # BaseScreen, BaseViewModel

  # 상태관리
  provider: ^6.0.5
  async: ^2.11.0
  rxdart: ^0.27.7

  # 라우팅
  go_router: ^6.5.5

  # DI
  get_it: ^7.2.0

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14

  # 네트워크
  dio: ^5.0.3
  http: ^0.13.5

  # Utils
  flutter_dotenv: ^5.0.2
  intl: ^0.18.1
  change_app_package_name: ^1.1.0

  # 앱 정보
  package_info_plus: ^4.1.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 800
    - family: staatliches
      fonts:
        - asset: assets/fonts/staatliches/Staatliches-Regular.ttf
          weight: 400
