name: techtalk
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Chat GPT
  chatgpt_completions: ^0.0.5

  # UI
  cupertino_will_pop_scope: ^1.2.1  #pop scope (스와이프 백 제스쳐 지원)
  after_layout: ^1.2.0 # Widget LifeCycle Mixin
  flutter_svg: ^2.0.5 # SVG 아이콘
  flutter_easyloading: ^3.0.5 # 로딩 UI 처리 관련
  flutter_chat_bubble: ^2.0.2 # 말풍선
  provider_screen: ^1.0.0 # BaseScreen, BaseViewModel

  # 상태관리
  provider: ^6.0.5
  async: ^2.11.0
  rxdart: ^0.27.7


  # 라우팅
  go_router: ^6.5.5

  # DI
  get_it: ^7.2.0

  # 네트워크
  dio: ^5.0.3
  http: ^0.13.5

  # Utils
  flutter_dotenv: ^5.0.2
  intl: ^0.18.1
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: pretendard_bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf

    - family: pretendard_semiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf

    - family: pretendard_regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf

    - family: pretendard_medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf

    - family: staatliches_regular
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
