name: techtalk
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #ChatGPT
  chatgpt_completions: ^1.0.2

  # UI
  cupertino_will_pop_scope: ^1.2.1  #pop scope (스와이프 백 제스쳐 지원)
  flutter_svg: ^2.0.5 # SVG 아이콘
  flutter_easyloading: ^3.0.5 # 로딩 UI 처리 관련
  fluttertoast: ^8.2.2
  flutter_chat_bubble: ^2.0.2 # 말풍선
  font_awesome_flutter: ^10.5.0
  flutter_hooks: ^0.20.1
  smooth_page_indicator: ^1.1.0
  animations: ^2.0.8
  flutter_animate: ^4.2.0+1


  # 상태관리
  provider: ^6.0.5
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  rxdart: ^0.27.7

  # 라우팅
  go_router: ^11.0.0

  # DI
  get_it: ^7.2.0

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14

  # 네트워크
  dio: ^5.0.3
  retrofit: ^4.0.1


  # Utils
  async: ^2.11.0
  flutter_dotenv: ^5.0.2
  intl: ^0.18.1
  change_app_package_name: ^1.1.0
  freezed_annotation: ^2.4.1
  copy_with_extension: ^5.0.4 # Entity CopyWith 메소드 Generator
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  uuid: ^4.1.0

  # 앱 정보
  package_info_plus: ^4.1.0
  collection: ^1.17.1
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  go_router_builder: ^2.3.0
  riverpod_generator: ^2.3.2
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  retrofit_generator: ^7.0.8
  copy_with_extension_gen: ^5.0.4 # Entity CopyWith 메소드 Generator
  freezed: ^2.4.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/fonts/pretendard/
    - assets/fonts/staatliches/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - lib/core/constants/assets.dart
    - assets/character/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 800
    - family: staatliches
      fonts:
        - asset: assets/fonts/staatliches/Staatliches-Regular.ttf
          weight: 400
