name: techtalk
description: A new Flutter project.

publish_to: "none"

version: 1.0.10+26

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Gemini
  google_generative_ai: ^0.4.3
  chat_gpt_sdk: ^3.1.0

  record: ^5.1.2
  # UI
  cupertino_will_pop_scope: ^1.2.1 #pop scope (스와이프 백 제스쳐 지원)
  flutter_svg: ^2.0.5 # SVG 아이콘
  flutter_easyloading: ^3.0.5 # 로딩 UI 처리 관련
  fluttertoast: ^8.2.2 # 토스트
  flutter_chat_bubble: ^2.0.2 # 말풍선
  font_awesome_flutter: ^10.5.0 # 아이콘
  smooth_page_indicator: ^1.1.0 # pageview 인디케이터
  flutter_animate: ^4.2.0+1 # 간편 애니메이션 메소드 지원
  cached_network_image: ^3.3.0 # 네트워크 이미지 캐싱
  bounce_tapper: ^1.0.6
  local_hero: ^0.3.0
  defer_pointer: ^0.0.2 # Overflow 영역에도 터치를 보장할 수 있도록 도와주는 패키지
  gap: ^3.0.1 # 간격 위젯
  # 상태관리
  provider: ^6.0.5
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  rxdart: ^0.27.7
  flutter_hooks: ^0.20.1

  # 라우팅
  go_router: ^13.1.0

  # DI
  get_it: ^7.2.0

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.0.14
  firebase_crashlytics: ^3.0.15
  firebase_analytics: ^10.8.7

  # Auth
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1

  # 네트워크
  dio: ^5.0.3

  # 로컬 데이터베이스
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # 모델링
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Utils
  dart_openai: ^5.1.0 #Whisper 사용 목적
  speech_to_text: ^7.0.0 # 음성 인식
  crypto: ^3.0.3 # 해슁
  async: ^2.11.0 # 비동기 처리
  flutter_dotenv: ^5.0.2 # dotnev
  intl: ^0.19.0 # 포맷팅
  permission_handler: ^11.3.1 #각종 플랫폼 권한 허용 및 감지
  uuid: ^4.1.0 # uuid 제너레이터
  image_picker: ^1.0.5 # 갤러리 접근
  single_import_generator: ^1.0.0 # barrel file generator
  lorem_ipsum_generator: ^0.0.1 # 랜던 텍스트 generator(삭제 예정)
  app_settings: ^5.1.1 # Device Setting Route
  korean_profanity_filter: ^1.0.0 # 비속어 욕설 필터링
  icons_launcher: ^2.1.7 # 앱 아이콘
  in_app_review: ^2.0.8 # 인앱 리뷰
  url_launcher: ^6.2.5 # url 런쳐
  connectivity_plus: ^5.0.2 # 네트워크 연결 상태 관리합
  easy_localization: ^3.0.0 # 다국어 지원
  collection: ^1.18.0 # 콜렉션 타입 익스텐션 지원 메소드
  # 앱 정보
  package_info_plus: ^8.0.2 # 현재 앱 버전 정보
  pub_semver: ^2.1.4 # 주부수 버전 비교 연산

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  go_router_builder: ^2.4.1
  build_verify: any
  riverpod_generator: ^2.3.2
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  retrofit_generator: ^7.0.8
  freezed: ^2.4.3
  analyzer: ^6.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/fonts/pretendard/
    - assets/icons/
    - assets/images/
    - assets/character/
    - assets/json/
    - assets/translations/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 800
