name: moon_dap
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Chat GPT
  chatgpt_completions: ^0.0.5

  # UI
  cupertino_will_pop_scope: ^1.2.1  #pop scope (스와이프 백 제스쳐 지원)

  # 상태관리
  provider: ^6.0.5

  # 라우팅
  go_router: ^6.5.5

  # 네트워크
  dio: ^5.0.3
  http: ^0.13.5

  # Utils
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: pretendard_bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf

    - family: pretendard_semiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf

    - family: pretendard_regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf

    - family: pretendard_medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf

    - family: staatliches_regular
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
