import 'package:techtalk/app/di/locator.dart';
import 'package:techtalk/features/topic/data/local/topic_local_data_source.dart';
import 'package:techtalk/features/topic/data/remote/topic_remote_data_source.dart';
import 'package:techtalk/features/topic/repositories/topic_repository.dart';
import 'package:techtalk/features/topic/usecases/get_categorized_topics_use_case.dart';
import 'package:techtalk/features/topic/usecases/get_topic_qna_use_case.dart';
import 'package:techtalk/features/topic/usecases/get_topic_qnas_use_case.dart';
import 'package:techtalk/features/topic/usecases/get_topic_use_case.dart';
import 'package:techtalk/features/topic/usecases/get_topics_use_case.dart';
import 'package:techtalk/features/topic/usecases/search_topics_use_case.dart';

export 'data/local/topic_local_data_source.dart';
export 'data/models/topic_category_model.dart';
export 'data/models/topic_model.dart';
export 'data/models/topic_qna_model.dart';
export 'data/remote/topic_remote_data_source.dart';
export 'entities/topic_category_entity.dart';
export 'entities/topic_entity.dart';
export 'entities/topic_qna_entity.dart';
export 'repositories/topic_repository.dart';
export 'usecases/get_categorized_topics_use_case.dart';
export 'usecases/get_topic_qna_use_case.dart';
export 'usecases/get_topic_qnas_use_case.dart';
export 'usecases/get_topic_use_case.dart';
export 'usecases/get_topics_use_case.dart';
export 'usecases/search_topics_use_case.dart';

final topicLocalDataSource = locator<TopicLocalDataSource>();
final topicRemoteDataSource = locator<TopicRemoteDataSource>();
final topicRepository = locator<TopicRepository>();
final getTopicsUseCase = locator<GetTopicsUseCase>();
final getCategorizedTopicsUseCase = locator<GetCategorizedTopicsUseCase>();
final getTopicUseCase = locator<GetTopicUseCase>();
final searchTopicsUseCase = locator<SearchTopicsUseCase>();
final getTopicQnasUseCase = locator<GetTopicQnasUseCase>();
final getTopicQnaUseCase = locator<GetTopicQnaUseCase>();
