import 'package:techtalk/app/di/locator.dart';
import 'package:techtalk/features/chat/data/remote/chat_remote_data_source.dart';
import 'package:techtalk/features/chat/repositories/chat_repository.dart';
import 'package:techtalk/features/chat/use_cases/create_interview_room_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_answer_feedback_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_chat_messages_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_chat_qnas_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_interview_room_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_interview_rooms_use_case.dart';
import 'package:techtalk/features/chat/use_cases/retrieve_qna_list_from_chat_list_use_case.dart';
import 'package:techtalk/features/chat/use_cases/update_chat_info_use_case.dart';

export 'chat.dart';
export 'entities/chat_room_entity.dart';
export 'entities/enums/answer_state.enum.dart';
export 'entities/enums/chat_type.enum.dart';
export 'entities/enums/interview_progress_state.enum.dart';
export 'entities/enums/pass_or_fail.enum.dart';
export 'entities/enums/reply_state.enum.dart';
export 'entities/feedback_message_entity.dart';
export 'entities/guide_message_entity.dart';
export 'entities/interview_qna_entity.dart';
export 'entities/interview_question_entity.dart';
export 'entities/message_entity.dart';
export 'entities/question_message_entity.dart';
export 'entities/sent_message_entity.dart';
export 'entities/user_interview_response.dart';
export 'repositories/chat_repository.dart';
export 'repositories/chat_repository_impl.dart';
export 'use_cases/get_answer_feedback_use_case.dart';
export 'use_cases/get_chat_messages_use_case.dart';
export 'use_cases/get_chat_qnas_use_case.dart';
export 'use_cases/get_interview_room_use_case.dart';
export 'use_cases/get_interview_rooms_use_case.dart';
export 'use_cases/retrieve_qna_list_from_chat_list_use_case.dart';

final chatRemoteDataSource = locator<ChatRemoteDataSource>();
final chatRepository = locator<ChatRepository>();
final getChatMessagesUseCase = locator<GetChatHistoryUseCase>();
final getAnswerFeedBackUseCase = locator<GetAnswerFeedbackUseCase>();
final retrieveQnaListFromChatListUseCase =
    locator<RetrieveQnaListFromChatListUseCase>();
final getInterviewRoomsUseCase = locator<GetInterviewRoomsUseCase>();
final updateChatInfoUseCase = locator<UpdateChatInfoUseCase>();
final createInterviewRoomUseCase = locator<CreateInterviewRoomUseCase>();
final getInterviewRoomUseCase = locator<GetInterviewRoomUseCase>();
final getChatQnAsUseCase = locator<GetChatQnAsUseCase>();
