import 'package:techtalk/app/di/app_binding.dart';
import 'package:techtalk/features/chat/data_source/remote/chat_remote_data_source.dart';
import 'package:techtalk/features/chat/repositories/chat_repository.dart';
import 'package:techtalk/features/chat/use_cases/create_chat_messages_use_case.dart';
import 'package:techtalk/features/chat/use_cases/create_chat_room_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_answer_feedback_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_chat_message_history_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_chat_qnas_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_chat_room_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_chat_rooms_use_case.dart';
import 'package:techtalk/features/chat/use_cases/get_random_qnas_use_case.dart';
import 'package:techtalk/features/chat/use_cases/report_chat_use_case.dart';

export 'chat.dart';
export 'repositories/chat_repository.dart';
export 'repositories/chat_repository_impl.dart';
export 'repositories/entities/answer_chat_message_entity.dart';
export 'repositories/entities/chat_message_entity.dart';
export 'repositories/entities/chat_qna_entity.dart';
export 'repositories/entities/chat_room_entity.dart';
export 'repositories/entities/feedback_chat_message_entity.dart';
export 'repositories/entities/guide_chat_message_entity.dart';
export 'repositories/entities/question_chat_message_entity.dart';
export 'repositories/enums/answer_state.enum.dart';
export 'repositories/enums/chat_result.enum.dart';
export 'repositories/enums/chat_room_progress.enum.dart';
export 'repositories/enums/chat_type.enum.dart';
export 'repositories/enums/feedback_progress.dart';
export 'use_cases/create_chat_messages_use_case.dart';
export 'use_cases/get_answer_feedback_use_case.dart';
export 'use_cases/get_chat_message_history_use_case.dart';
export 'use_cases/get_chat_qnas_use_case.dart';
export 'use_cases/get_chat_room_use_case.dart';
export 'use_cases/report_chat_use_case.dart';

final chatRemoteDataSource = locator<ChatRemoteDataSource>();
final chatRepository = locator<ChatRepository>();
final getChatMessageHistoryUseCase = locator<GetChatMessageHistoryUseCase>();
final getAnswerFeedBackUseCase = locator<GetAnswerFeedbackUseCase>();
final createChatMessagesUseCase = locator<CreateChatMessagesUseCase>();
final createChatRoomUseCase = locator<CreateChatRoomUseCase>();
final getChatRoomUseCase = locator<GetChatRoomUseCase>();
final getChatRoomsUseCase = locator<GetChatRoomsUseCase>();
final getChatQnasUseCase = locator<GetChatQnasUseCase>();
final reportChatUseCase = locator<ReportChatUseCase>();
final getRandomQnaUseCase = locator<GetRandomQnasUseCase>();
