///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsArrowLeft = 'assets/icons/arrow_left.svg';
  static const String iconsAvatar1 = 'assets/icons/avatar_1.svg';
  static const String iconsCorrect = 'assets/icons/correct.svg';
  static const String iconsGoogleLogo = 'assets/icons/google_logo.svg';
  static const String iconsIncorrect = 'assets/icons/incorrect.svg';
  static const String iconsMoreCircle = 'assets/icons/more_circle.svg';
  static const String iconsSend = 'assets/icons/send.svg';
  static const String imagesAvatar1 = 'assets/images/avatar_1.png';
  static const String imagesWelcomeTechtalk =
      'assets/images/welcome_techtalk.svg';
  static const String logoTechTalkLogo = 'assets/logo/tech_talk_logo.svg';
  static const String pretendardPretendardBold =
      'assets/fonts/pretendard/Pretendard-Bold.otf';
  static const String pretendardPretendardMedium =
      'assets/fonts/pretendard/Pretendard-Medium.otf';
  static const String pretendardPretendardRegular =
      'assets/fonts/pretendard/Pretendard-Regular.otf';
  static const String pretendardPretendardSemiBold =
      'assets/fonts/pretendard/Pretendard-SemiBold.otf';
  static const String staatlichesStaatlichesRegular =
      'assets/fonts/staatliches/Staatliches-Regular.ttf';
  static const String techTalk = '.env';
}
