///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String characterBlue01 = 'assets/character/blue_01.svg';
  static const String characterBlue02 = 'assets/character/blue_02.svg';
  static const String characterBlue03 = 'assets/character/blue_03.svg';
  static const String characterBlue04 = 'assets/character/blue_04.svg';
  static const String characterBlue05 = 'assets/character/blue_05.svg';
  static const String characterBlue06 = 'assets/character/blue_06.svg';
  static const String characterBlue07 = 'assets/character/blue_07.svg';
  static const String characterGreen01 = 'assets/character/green_01.svg';
  static const String characterGreen02 = 'assets/character/green_02.svg';
  static const String characterGreen03 = 'assets/character/green_03.svg';
  static const String characterGreen04 = 'assets/character/green_04.svg';
  static const String characterGreen05 = 'assets/character/green_05.svg';
  static const String characterGreen06 = 'assets/character/green_06.svg';
  static const String characterGreen07 = 'assets/character/green_07.svg';
  static const String characterPurple01 = 'assets/character/purple_01.svg';
  static const String characterPurple02 = 'assets/character/purple_02.svg';
  static const String characterPurple03 = 'assets/character/purple_03.svg';
  static const String characterPurple04 = 'assets/character/purple_04.svg';
  static const String characterPurple05 = 'assets/character/purple_05.svg';
  static const String characterPurple06 = 'assets/character/purple_06.svg';
  static const String characterPurple07 = 'assets/character/purple_07.svg';
  static const String characterRed01 = 'assets/character/red_01.svg';
  static const String characterRed02 = 'assets/character/red_02.svg';
  static const String characterRed03 = 'assets/character/red_03.svg';
  static const String characterRed04 = 'assets/character/red_04.svg';
  static const String characterRed05 = 'assets/character/red_05.svg';
  static const String characterRed06 = 'assets/character/red_06.svg';
  static const String characterRed07 = 'assets/character/red_07.svg';
  static const String iconsArrowDown = 'assets/icons/arrow_down.svg';
  static const String iconsArrowDownThick = 'assets/icons/arrow_down_thick.svg';
  static const String iconsArrowLeft = 'assets/icons/arrow_left.svg';
  static const String iconsArrowLeftThick = 'assets/icons/arrow_left_thick.svg';
  static const String iconsArrowRight = 'assets/icons/arrow_right.svg';
  static const String iconsArrowRightThick =
      'assets/icons/arrow_right_thick.svg';
  static const String iconsArrowUp = 'assets/icons/arrow_up.svg';
  static const String iconsArrowUpThick = 'assets/icons/arrow_up_thick.svg';
  static const String iconsAvatar1 = 'assets/icons/avatar_1.svg';
  static const String iconsBullet = 'assets/icons/bullet.svg';
  static const String iconsCamera = 'assets/icons/camera.svg';
  static const String iconsCheck = 'assets/icons/check.svg';
  static const String iconsCheckThick = 'assets/icons/check_thick.svg';
  static const String iconsClose = 'assets/icons/close.svg';
  static const String iconsCloseThick = 'assets/icons/close_thick.svg';
  static const String iconsCorrect = 'assets/icons/correct.svg';
  static const String iconsCorrectIndicator =
      'assets/icons/correct_indicator.svg';
  static const String iconsDataStructure = 'assets/icons/data_structure.svg';
  static const String iconsExpansionArrowIndicator =
      'assets/icons/expansion_arrow_indicator.svg';
  static const String iconsGoogleLogo = 'assets/icons/google_logo.svg';
  static const String iconsHome = 'assets/icons/home.svg';
  static const String iconsIncorrect = 'assets/icons/incorrect.svg';
  static const String iconsMenu = 'assets/icons/menu.svg';
  static const String iconsMenuThick = 'assets/icons/menu_thick.svg';
  static const String iconsMoreCircle = 'assets/icons/more_circle.svg';
  static const String iconsNote = 'assets/icons/note.svg';
  static const String iconsPencil = 'assets/icons/pencil.svg';
  static const String iconsPlus = 'assets/icons/plus.svg';
  static const String iconsPlusThick = 'assets/icons/plus_thick.svg';
  static const String iconsRoundedCamera = 'assets/icons/rounded_camera.svg';
  static const String iconsRoundedCheck = 'assets/icons/rounded_check.svg';
  static const String iconsRoundedCheckSmallBlue =
      'assets/icons/rounded_check_small_blue.svg';
  static const String iconsRoundedCheckThick =
      'assets/icons/rounded_check_thick.svg';
  static const String iconsRoundedClose = 'assets/icons/rounded_close.svg';
  static const String iconsRoundedCloseSmallRed =
      'assets/icons/rounded_close_small_red.svg';
  static const String iconsRoundedCloseThick =
      'assets/icons/rounded_close_thick.svg';
  static const String iconsRoundedExclamation =
      'assets/icons/rounded_exclamation.svg';
  static const String iconsRoundedMore = 'assets/icons/rounded_more.svg';
  static const String iconsRoundedOs = 'assets/icons/rounded_os.svg';
  static const String iconsRoundedPlusBig = 'assets/icons/rounded_plus_big.svg';
  static const String iconsRoundedTop = 'assets/icons/rounded_top.svg';
  static const String iconsRoundedWarnningSmallRed =
      'assets/icons/rounded_warnning_small_red.svg';
  static const String iconsSearch = 'assets/icons/search.svg';
  static const String iconsSearchThick = 'assets/icons/search_thick.svg';
  static const String iconsSend = 'assets/icons/send.svg';
  static const String iconsStudy = 'assets/icons/study.svg';
  static const String iconsTalker = 'assets/icons/talker.svg';
  static const String iconsUser = 'assets/icons/user.svg';
  static const String iconsWarnning = 'assets/icons/warnning.svg';
  static const String iconsWrongIndicator = 'assets/icons/wrong_indicator.svg';
  static const String imagesAvatar1 = 'assets/images/avatar_1.png';
  static const String imagesBlankProfile = 'assets/images/blank_profile.png';
  static const String imagesSparkle = 'assets/images/sparkle.svg';
  static const String imagesSplashImage = 'assets/images/splash_image.png';
  static const String imagesTopicAndroid = 'assets/images/topic_android.png';
  static const String imagesTopicDataStructure =
      'assets/images/topic_data_structure.png';
  static const String imagesTopicFlutter = 'assets/images/topic_flutter.png';
  static const String imagesTopicIos = 'assets/images/topic_ios.png';
  static const String imagesTopicJava = 'assets/images/topic_java.png';
  static const String imagesTopicNestJs = 'assets/images/topic_nest_js.png';
  static const String imagesTopicOperatingSystem =
      'assets/images/topic_operating_system.png';
  static const String imagesTopicReact = 'assets/images/topic_react.png';
  static const String imagesTopicSpring = 'assets/images/topic_spring.png';
  static const String imagesTopicSwift = 'assets/images/topic_swift.png';
  static const String imagesWelcomeTechtalk =
      'assets/images/welcome_techtalk.svg';
  static const String jsonTopicCategoriesData =
      'assets/json/topic_categories_data.json';
  static const String logoTechTalkLogo = 'assets/logo/tech_talk_logo.svg';
  static const String pretendardPretendardBold =
      'assets/fonts/pretendard/Pretendard-Bold.otf';
  static const String pretendardPretendardMedium =
      'assets/fonts/pretendard/Pretendard-Medium.otf';
  static const String pretendardPretendardRegular =
      'assets/fonts/pretendard/Pretendard-Regular.otf';
  static const String pretendardPretendardSemiBold =
      'assets/fonts/pretendard/Pretendard-SemiBold.otf';
  static const String staatlichesStaatlichesRegular =
      'assets/fonts/staatliches/Staatliches-Regular.ttf';
  static const String techTalk = '.env';
}
